// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

import ProductStatus from "./ProductStatus";

export const product = {
    ProductStatus,
}

export default product