// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.


/**
 * @see [App\enum\product\ProductStatus](C:\xampp\htdocs\agrilink_cmr\app\enum\product\ProductStatus.php)
 */
export const ProductStatus = {  } as const

export default ProductStatus