// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

export const PERSON = "person"
export const COMPANY = "company"

/**
 * @see [App\enum\buyer\BuyerTypeEnum](C:\xampp\htdocs\AgriLink-Cameroun\app\enum\buyer\BuyerTypeEnum.php)
 */
export const BuyerTypeEnum = { PERSON, COMPANY } as const

export default BuyerTypeEnum