// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.


/**
 * @see [App\enum\buyer\BuyerTypeEnum](C:\xampp\htdocs\agrilink_cmr\app\enum\buyer\BuyerTypeEnum.php)
 */
export const BuyerTypeEnum = {  } as const

export default BuyerTypeEnum