// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

import BuyerTypeEnum from "./BuyerTypeEnum";

export const buyer = {
    BuyerTypeEnum,
}

export default buyer