// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

import ReportEnum from "./ReportEnum";

export const report = {
    ReportEnum,
}

export default report