// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.


/**
 * @see [App\enum\report\ReportEnum](C:\xampp\htdocs\agrilink_cmr\app\enum\report\ReportEnum.php)
 */
export const ReportEnum = {  } as const

export default ReportEnum