// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

import enum from "./enum";

export const App = {
    enum,
}

export default App