// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

import { formSafeOptions, queryParams, type RouteDefinition, type RouteFormDefinition, type RouteQueryOptions } from "./../index";

/**
 * @see \C:\xampp\htdocs\AgriLink-Cameroun\routes\web.php:6
 * @route "/"
 */
export const home = (options?: RouteQueryOptions): RouteDefinition<"get"> => ({
    url: home.url(options),
    method: "get",
})

home.definition = {
    methods: ["get","head"],
    url: "/",
} satisfies RouteDefinition<["get","head"]>

/**
 * @see \C:\xampp\htdocs\AgriLink-Cameroun\routes\web.php:6
 * @route "/"
 */
home.url = (options?: RouteQueryOptions) => {
    return home.definition.url + queryParams(options)
}

/**
 * @see \C:\xampp\htdocs\AgriLink-Cameroun\routes\web.php:6
 * @route "/"
 */
home.get = (options?: RouteQueryOptions): RouteDefinition<"get"> => ({
    url: home.url(options),
    method: "get",
})

/**
 * @see \C:\xampp\htdocs\AgriLink-Cameroun\routes\web.php:6
 * @route "/"
 */
home.head = (options?: RouteQueryOptions): RouteDefinition<"head"> => ({
    url: home.url(options),
    method: "head",
})



/**
 * @see \C:\xampp\htdocs\AgriLink-Cameroun\routes\web.php:6
 * @route "/"
 */
const homeForm = (options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: home.url(options),
    method: "get",
})

/**
 * @see \C:\xampp\htdocs\AgriLink-Cameroun\routes\web.php:6
 * @route "/"
 */
homeForm.get = (options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: home.url(options),
    method: "get",
})

/**
 * @see \C:\xampp\htdocs\AgriLink-Cameroun\routes\web.php:6
 * @route "/"
 */
homeForm.head = (options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: home.url(formSafeOptions("head", options)),
    method: "get",
})



home.form = homeForm
/**
 * @see \C:\xampp\htdocs\AgriLink-Cameroun\routes\web.php:11
 * @route "/login"
 */
export const loginForm = (options?: RouteQueryOptions): RouteDefinition<"get"> => ({
    url: loginForm.url(options),
    method: "get",
})

loginForm.definition = {
    methods: ["get","head"],
    url: "/login",
} satisfies RouteDefinition<["get","head"]>

/**
 * @see \C:\xampp\htdocs\AgriLink-Cameroun\routes\web.php:11
 * @route "/login"
 */
loginForm.url = (options?: RouteQueryOptions) => {
    return loginForm.definition.url + queryParams(options)
}

/**
 * @see \C:\xampp\htdocs\AgriLink-Cameroun\routes\web.php:11
 * @route "/login"
 */
loginForm.get = (options?: RouteQueryOptions): RouteDefinition<"get"> => ({
    url: loginForm.url(options),
    method: "get",
})

/**
 * @see \C:\xampp\htdocs\AgriLink-Cameroun\routes\web.php:11
 * @route "/login"
 */
loginForm.head = (options?: RouteQueryOptions): RouteDefinition<"head"> => ({
    url: loginForm.url(options),
    method: "head",
})



/**
 * @see \C:\xampp\htdocs\AgriLink-Cameroun\routes\web.php:11
 * @route "/login"
 */
const loginFormForm = (options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: loginForm.url(options),
    method: "get",
})

/**
 * @see \C:\xampp\htdocs\AgriLink-Cameroun\routes\web.php:11
 * @route "/login"
 */
loginFormForm.get = (options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: loginForm.url(options),
    method: "get",
})

/**
 * @see \C:\xampp\htdocs\AgriLink-Cameroun\routes\web.php:11
 * @route "/login"
 */
loginFormForm.head = (options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: loginForm.url(formSafeOptions("head", options)),
    method: "get",
})



loginForm.form = loginFormForm
/**
 * @see \C:\xampp\htdocs\AgriLink-Cameroun\routes\web.php:14
 * @route "/register"
 */
export const registerForm = (options?: RouteQueryOptions): RouteDefinition<"get"> => ({
    url: registerForm.url(options),
    method: "get",
})

registerForm.definition = {
    methods: ["get","head"],
    url: "/register",
} satisfies RouteDefinition<["get","head"]>

/**
 * @see \C:\xampp\htdocs\AgriLink-Cameroun\routes\web.php:14
 * @route "/register"
 */
registerForm.url = (options?: RouteQueryOptions) => {
    return registerForm.definition.url + queryParams(options)
}

/**
 * @see \C:\xampp\htdocs\AgriLink-Cameroun\routes\web.php:14
 * @route "/register"
 */
registerForm.get = (options?: RouteQueryOptions): RouteDefinition<"get"> => ({
    url: registerForm.url(options),
    method: "get",
})

/**
 * @see \C:\xampp\htdocs\AgriLink-Cameroun\routes\web.php:14
 * @route "/register"
 */
registerForm.head = (options?: RouteQueryOptions): RouteDefinition<"head"> => ({
    url: registerForm.url(options),
    method: "head",
})



/**
 * @see \C:\xampp\htdocs\AgriLink-Cameroun\routes\web.php:14
 * @route "/register"
 */
const registerFormForm = (options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: registerForm.url(options),
    method: "get",
})

/**
 * @see \C:\xampp\htdocs\AgriLink-Cameroun\routes\web.php:14
 * @route "/register"
 */
registerFormForm.get = (options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: registerForm.url(options),
    method: "get",
})

/**
 * @see \C:\xampp\htdocs\AgriLink-Cameroun\routes\web.php:14
 * @route "/register"
 */
registerFormForm.head = (options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: registerForm.url(formSafeOptions("head", options)),
    method: "get",
})



registerForm.form = registerFormForm

const routes = {
    home,
    loginForm,
    registerForm,
}

export default routes