// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

import { formSafeOptions, queryParams, type RouteDefinition, type RouteFormDefinition, type RouteQueryOptions } from "./../index";

/**
 * @see \C:\xampp\htdocs\AgriLink-Cameroun\routes\web.php:9
 * @route "/"
 */
export const home = (options?: RouteQueryOptions): RouteDefinition<"get"> => ({
    url: home.url(options),
    method: "get",
})

home.definition = {
    methods: ["get","head"],
    url: "/",
} satisfies RouteDefinition<["get","head"]>

/**
 * @see \C:\xampp\htdocs\AgriLink-Cameroun\routes\web.php:9
 * @route "/"
 */
home.url = (options?: RouteQueryOptions) => {
    return home.definition.url + queryParams(options)
}

/**
 * @see \C:\xampp\htdocs\AgriLink-Cameroun\routes\web.php:9
 * @route "/"
 */
home.get = (options?: RouteQueryOptions): RouteDefinition<"get"> => ({
    url: home.url(options),
    method: "get",
})

/**
 * @see \C:\xampp\htdocs\AgriLink-Cameroun\routes\web.php:9
 * @route "/"
 */
home.head = (options?: RouteQueryOptions): RouteDefinition<"head"> => ({
    url: home.url(options),
    method: "head",
})



/**
 * @see \C:\xampp\htdocs\AgriLink-Cameroun\routes\web.php:9
 * @route "/"
 */
const homeForm = (options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: home.url(options),
    method: "get",
})

/**
 * @see \C:\xampp\htdocs\AgriLink-Cameroun\routes\web.php:9
 * @route "/"
 */
homeForm.get = (options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: home.url(options),
    method: "get",
})

/**
 * @see \C:\xampp\htdocs\AgriLink-Cameroun\routes\web.php:9
 * @route "/"
 */
homeForm.head = (options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: home.url(formSafeOptions("head", options)),
    method: "get",
})



home.form = homeForm
/**
 * @see \C:\xampp\htdocs\AgriLink-Cameroun\routes\web.php:14
 * @route "/login"
 */
export const connexion = (options?: RouteQueryOptions): RouteDefinition<"get"> => ({
    url: connexion.url(options),
    method: "get",
})

connexion.definition = {
    methods: ["get","head"],
    url: "/login",
} satisfies RouteDefinition<["get","head"]>

/**
 * @see \C:\xampp\htdocs\AgriLink-Cameroun\routes\web.php:14
 * @route "/login"
 */
connexion.url = (options?: RouteQueryOptions) => {
    return connexion.definition.url + queryParams(options)
}

/**
 * @see \C:\xampp\htdocs\AgriLink-Cameroun\routes\web.php:14
 * @route "/login"
 */
connexion.get = (options?: RouteQueryOptions): RouteDefinition<"get"> => ({
    url: connexion.url(options),
    method: "get",
})

/**
 * @see \C:\xampp\htdocs\AgriLink-Cameroun\routes\web.php:14
 * @route "/login"
 */
connexion.head = (options?: RouteQueryOptions): RouteDefinition<"head"> => ({
    url: connexion.url(options),
    method: "head",
})



/**
 * @see \C:\xampp\htdocs\AgriLink-Cameroun\routes\web.php:14
 * @route "/login"
 */
const connexionForm = (options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: connexion.url(options),
    method: "get",
})

/**
 * @see \C:\xampp\htdocs\AgriLink-Cameroun\routes\web.php:14
 * @route "/login"
 */
connexionForm.get = (options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: connexion.url(options),
    method: "get",
})

/**
 * @see \C:\xampp\htdocs\AgriLink-Cameroun\routes\web.php:14
 * @route "/login"
 */
connexionForm.head = (options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: connexion.url(formSafeOptions("head", options)),
    method: "get",
})



connexion.form = connexionForm
/**
 * @see \C:\xampp\htdocs\AgriLink-Cameroun\routes\web.php:17
 * @route "/register"
 */
export const inscription = (options?: RouteQueryOptions): RouteDefinition<"get"> => ({
    url: inscription.url(options),
    method: "get",
})

inscription.definition = {
    methods: ["get","head"],
    url: "/register",
} satisfies RouteDefinition<["get","head"]>

/**
 * @see \C:\xampp\htdocs\AgriLink-Cameroun\routes\web.php:17
 * @route "/register"
 */
inscription.url = (options?: RouteQueryOptions) => {
    return inscription.definition.url + queryParams(options)
}

/**
 * @see \C:\xampp\htdocs\AgriLink-Cameroun\routes\web.php:17
 * @route "/register"
 */
inscription.get = (options?: RouteQueryOptions): RouteDefinition<"get"> => ({
    url: inscription.url(options),
    method: "get",
})

/**
 * @see \C:\xampp\htdocs\AgriLink-Cameroun\routes\web.php:17
 * @route "/register"
 */
inscription.head = (options?: RouteQueryOptions): RouteDefinition<"head"> => ({
    url: inscription.url(options),
    method: "head",
})



/**
 * @see \C:\xampp\htdocs\AgriLink-Cameroun\routes\web.php:17
 * @route "/register"
 */
const inscriptionForm = (options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: inscription.url(options),
    method: "get",
})

/**
 * @see \C:\xampp\htdocs\AgriLink-Cameroun\routes\web.php:17
 * @route "/register"
 */
inscriptionForm.get = (options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: inscription.url(options),
    method: "get",
})

/**
 * @see \C:\xampp\htdocs\AgriLink-Cameroun\routes\web.php:17
 * @route "/register"
 */
inscriptionForm.head = (options?: RouteQueryOptions): RouteFormDefinition<"get"> => ({
    action: inscription.url(formSafeOptions("head", options)),
    method: "get",
})



inscription.form = inscriptionForm
/**
 * @see \App\Http\Controllers\AuthController::login
 * @see \C:\xampp\htdocs\AgriLink-Cameroun\app\Http\Controllers\AuthController.php:54
 * @route "/login"
 */
export const login = (options?: RouteQueryOptions): RouteDefinition<"post"> => ({
    url: login.url(options),
    method: "post",
})

login.definition = {
    methods: ["post"],
    url: "/login",
} satisfies RouteDefinition<["post"]>

/**
 * @see \App\Http\Controllers\AuthController::login
 * @see \C:\xampp\htdocs\AgriLink-Cameroun\app\Http\Controllers\AuthController.php:54
 * @route "/login"
 */
login.url = (options?: RouteQueryOptions) => {
    return login.definition.url + queryParams(options)
}

/**
 * @see \App\Http\Controllers\AuthController::login
 * @see \C:\xampp\htdocs\AgriLink-Cameroun\app\Http\Controllers\AuthController.php:54
 * @route "/login"
 */
login.post = (options?: RouteQueryOptions): RouteDefinition<"post"> => ({
    url: login.url(options),
    method: "post",
})



/**
 * @see \App\Http\Controllers\AuthController::login
 * @see \C:\xampp\htdocs\AgriLink-Cameroun\app\Http\Controllers\AuthController.php:54
 * @route "/login"
 */
const loginForm = (options?: RouteQueryOptions): RouteFormDefinition<"post"> => ({
    action: login.url(options),
    method: "post",
})

/**
 * @see \App\Http\Controllers\AuthController::login
 * @see \C:\xampp\htdocs\AgriLink-Cameroun\app\Http\Controllers\AuthController.php:54
 * @route "/login"
 */
loginForm.post = (options?: RouteQueryOptions): RouteFormDefinition<"post"> => ({
    action: login.url(options),
    method: "post",
})



login.form = loginForm
/**
 * @see \App\Http\Controllers\AuthController::register
 * @see \C:\xampp\htdocs\AgriLink-Cameroun\app\Http\Controllers\AuthController.php:17
 * @route "/register"
 */
export const register = (options?: RouteQueryOptions): RouteDefinition<"post"> => ({
    url: register.url(options),
    method: "post",
})

register.definition = {
    methods: ["post"],
    url: "/register",
} satisfies RouteDefinition<["post"]>

/**
 * @see \App\Http\Controllers\AuthController::register
 * @see \C:\xampp\htdocs\AgriLink-Cameroun\app\Http\Controllers\AuthController.php:17
 * @route "/register"
 */
register.url = (options?: RouteQueryOptions) => {
    return register.definition.url + queryParams(options)
}

/**
 * @see \App\Http\Controllers\AuthController::register
 * @see \C:\xampp\htdocs\AgriLink-Cameroun\app\Http\Controllers\AuthController.php:17
 * @route "/register"
 */
register.post = (options?: RouteQueryOptions): RouteDefinition<"post"> => ({
    url: register.url(options),
    method: "post",
})



/**
 * @see \App\Http\Controllers\AuthController::register
 * @see \C:\xampp\htdocs\AgriLink-Cameroun\app\Http\Controllers\AuthController.php:17
 * @route "/register"
 */
const registerForm = (options?: RouteQueryOptions): RouteFormDefinition<"post"> => ({
    action: register.url(options),
    method: "post",
})

/**
 * @see \App\Http\Controllers\AuthController::register
 * @see \C:\xampp\htdocs\AgriLink-Cameroun\app\Http\Controllers\AuthController.php:17
 * @route "/register"
 */
registerForm.post = (options?: RouteQueryOptions): RouteFormDefinition<"post"> => ({
    action: register.url(options),
    method: "post",
})



register.form = registerForm

const routes = {
    home,
    connexion,
    inscription,
    login,
    register,
}

export default routes