// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

import storage from "./storage";

export const routes = {
    storage,
}

export default routes