// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

import { queryParams, type RouteDefinition, type RouteFormDefinition, type RouteQueryOptions } from "./../../../index";

/**
 * @see \App\Http\Controllers\AuthController::login
 * @see \C:\xampp\htdocs\AgriLink-Cameroun\app\Http\Controllers\AuthController.php:54
 * @route "/login"
 */
export const login = (options?: RouteQueryOptions): RouteDefinition<"post"> => ({
    url: login.url(options),
    method: "post",
})

login.definition = {
    methods: ["post"],
    url: "/login",
} satisfies RouteDefinition<["post"]>

/**
 * @see \App\Http\Controllers\AuthController::login
 * @see \C:\xampp\htdocs\AgriLink-Cameroun\app\Http\Controllers\AuthController.php:54
 * @route "/login"
 */
login.url = (options?: RouteQueryOptions) => {
    return login.definition.url + queryParams(options)
}

/**
 * @see \App\Http\Controllers\AuthController::login
 * @see \C:\xampp\htdocs\AgriLink-Cameroun\app\Http\Controllers\AuthController.php:54
 * @route "/login"
 */
login.post = (options?: RouteQueryOptions): RouteDefinition<"post"> => ({
    url: login.url(options),
    method: "post",
})



/**
 * @see \App\Http\Controllers\AuthController::login
 * @see \C:\xampp\htdocs\AgriLink-Cameroun\app\Http\Controllers\AuthController.php:54
 * @route "/login"
 */
const loginForm = (options?: RouteQueryOptions): RouteFormDefinition<"post"> => ({
    action: login.url(options),
    method: "post",
})

/**
 * @see \App\Http\Controllers\AuthController::login
 * @see \C:\xampp\htdocs\AgriLink-Cameroun\app\Http\Controllers\AuthController.php:54
 * @route "/login"
 */
loginForm.post = (options?: RouteQueryOptions): RouteFormDefinition<"post"> => ({
    action: login.url(options),
    method: "post",
})



login.form = loginForm
/**
 * @see \App\Http\Controllers\AuthController::register
 * @see \C:\xampp\htdocs\AgriLink-Cameroun\app\Http\Controllers\AuthController.php:17
 * @route "/register"
 */
export const register = (options?: RouteQueryOptions): RouteDefinition<"post"> => ({
    url: register.url(options),
    method: "post",
})

register.definition = {
    methods: ["post"],
    url: "/register",
} satisfies RouteDefinition<["post"]>

/**
 * @see \App\Http\Controllers\AuthController::register
 * @see \C:\xampp\htdocs\AgriLink-Cameroun\app\Http\Controllers\AuthController.php:17
 * @route "/register"
 */
register.url = (options?: RouteQueryOptions) => {
    return register.definition.url + queryParams(options)
}

/**
 * @see \App\Http\Controllers\AuthController::register
 * @see \C:\xampp\htdocs\AgriLink-Cameroun\app\Http\Controllers\AuthController.php:17
 * @route "/register"
 */
register.post = (options?: RouteQueryOptions): RouteDefinition<"post"> => ({
    url: register.url(options),
    method: "post",
})



/**
 * @see \App\Http\Controllers\AuthController::register
 * @see \C:\xampp\htdocs\AgriLink-Cameroun\app\Http\Controllers\AuthController.php:17
 * @route "/register"
 */
const registerForm = (options?: RouteQueryOptions): RouteFormDefinition<"post"> => ({
    action: register.url(options),
    method: "post",
})

/**
 * @see \App\Http\Controllers\AuthController::register
 * @see \C:\xampp\htdocs\AgriLink-Cameroun\app\Http\Controllers\AuthController.php:17
 * @route "/register"
 */
registerForm.post = (options?: RouteQueryOptions): RouteFormDefinition<"post"> => ({
    action: register.url(options),
    method: "post",
})



register.form = registerForm

const AuthController = {
    login,
    register,
}

export default AuthController