// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

import OrderEnum from "./OrderEnum";

export const order = {
    OrderEnum,
}

export default order