// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.


/**
 * @see [App\enum\order\OrderEnum](C:\xampp\htdocs\agrilink_cmr\app\enum\order\OrderEnum.php)
 */
export const OrderEnum = {  } as const

export default OrderEnum