// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

import UserRole from "./UserRole";
import buyer from "./buyer";
import order from "./order";
import product from "./product";
import report from "./report";

export const enum = {
    UserRole,
    buyer,
    order,
    product,
    report,
}

export default enum