// This file is auto-generated by Laravel Wayfinder.
// Do not edit this file directly, any changes will be overwritten.

export const ADMIN = "admin"
export const BUYER = "buyer"
export const FARMER = "farmer"

/**
 * @see [App\enum\UserRole](C:\xampp\htdocs\AgriLink-Cameroun\app\enum\UserRole.php)
 */
export const UserRole = { ADMIN, BUYER, FARMER } as const

export default UserRole